services:
  - type: web
    name: skillsxchangee
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      npm install
      npm run build
      php artisan key:generate --force --no-interaction
      php artisan config:cache --no-interaction
      php artisan route:cache --no-interaction
      php artisan view:cache --no-interaction
      php artisan storage:link --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: SkillsXchangee
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://skillsxchangee.onrender.com
      - key: LOG_CHANNEL
        value: stderr

      # ✅ MySQL on Railway (public connection)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_PORT
        value: "14460"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: lncQUGzAqadIdRckNFrZLgrIlgpKJPOx

      # ✅ Laravel-specific configs
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: FILESYSTEM_DISK
        value: public
