services:
  - type: web
    name: skillsxchangee
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      npm install
      npm run build
      php artisan key:generate --force --no-interaction
      php artisan config:cache --no-interaction
      php artisan route:cache --no-interaction
      php artisan view:cache --no-interaction
    startCommand: php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

  - type: pserv
    name: skillsxchangee-db
    env: mysql
    plan: free
    disk:
      name: skillsxchangee-db-disk
      mountPath: /var/lib/mysql
      sizeGB: 1
