services:
  - type: web
    name: skillsxchangee
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      npm install
      npm run build
      php artisan key:generate --force --no-interaction
      php artisan config:clear --no-interaction
      php artisan route:clear --no-interaction
      php artisan view:clear --no-interaction
      php artisan cache:clear --no-interaction
      php artisan optimize:clear --no-interaction
      php artisan storage:link --force
      chmod +x deploy.sh
    startCommand: ./start.sh
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: SkillsXchangee
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://skillsxchangee.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${MYSQLHOST}
      - key: DB_PORT
        value: ${MYSQLPORT}
      - key: DB_DATABASE
        value: ${MYSQLDATABASE}
      - key: DB_USERNAME
        value: ${MYSQLUSER}
      - key: DB_PASSWORD
        value: ${MYSQLPASSWORD}
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: FILESYSTEM_DISK
        value: public

  - type: pserv
    name: skillsxchangee-db
    env: mysql
    plan: free
    disk:
      name: skillsxchangee-db-disk
      mountPath: /var/lib/mysql
      sizeGB: 1
